version: '3.8'

services:
  kuluchashserver:
    image: kuluchashserver
    container_name: kuluchashserver
    restart: always
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SENDCHAMP_KEY: ${SENDCHAMP_KEY}
      DOJAH_ENDPOINT: ${DOJAH_ENDPOINT}
      DOJAH_API_KEY: ${DOJAH_API_KEY}
      DOJAH_SECRET_KEY: ${DOJAH_SECRET_KEY}
      DOJAH_APP_ID: ${DOJAH_APP_ID}
      CLOUD_CLOUD_NAME: ${CLOUD_CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}
    ports:
      - 3005:3000
    networks:
      - kulucash
    depends_on:
      - kulucash_db
    links:
      - kulucash_db
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  kulucash_db:
    image: postgres:15.3-alpine
    container_name: kulucash_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 30455:5432
    volumes:
      - kulucash_db_data:/var/lib/postgresql/data
    networks:
      - kulucash

networks:
  kulucash:

volumes:
  kulucash_db_data:
