version: '3.4'

services:
  kuluchashserver:
    image: kuluchashserver
    container_name: kuluchashserver
    restart: always
    pull_policy: build
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SENDCHAMP_KEY: ${SENDCHAMP_KEY}
      DOJAH_ENDPOINT: ${DOJAH_ENDPOINT}
      DOJAH_API_KEY: ${DOJAH_API_KEY}
      DOJAH_SECRET_KEY: ${DOJAH_SECRET_KEY}
      DOJAH_APP_ID: ${DOJAH_APP_ID}
    ports:
      - 3000:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
