version: '3.4'

services:
  kuluchashserver:
    image: kuluchashserver
    container_name: kuluchashserver
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SENDCHAMP_KEY: ${SENDCHAMP_KEY}
    ports:
      - 3000:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
