export const verifyObj = {
  status: true,
  data: {
    bvn: '22222222222',
    date_of_birth: '28-Jun-2000',
    email: 'ISAACTHOMPSONBROWN@YAHOO.COM',
    enrollment_bank: '058',
    enrollment_branch: 'UNILORIN',
    first_name: 'JOSHUA',
    gender: 'Male',
    image: '',
    last_name: 'ISAAC',
    level_of_account: 'Level 2 - Medium Level Accounts',
    lga_of_origin: 'Odo Otin',
    lga_of_residence: 'Ilorin South',
    marital_status: 'Single',
    middle_name: 'THOMPSONBROWN',
    name_on_card: 'ISAAC, THOMPSON O',
    nationality: 'Nigeria',
    nin: '',
    phone_number1: '07012345678',
    phone_number2: '',
    registration_date: '21-Mar-2018',
    residential_address: '24, OSHODI SURULERE, ILORIN',
    state_of_origin: 'Osun State',
    state_of_residence: 'Kwara State',
    title: 'Mr',
    watch_listed: 'NO',
    customer: 'fef2fbc6-d4d8-43b0-9877-359d8a2877f2',
    status: 200,
  },
  message: 'BVN Verified',
};
