import { CreateUserDto } from '../dto/create_user.dto';

export const createUserObj: CreateUserDto = {
  first_name: '',
  middle_name: '',
  last_name: '',
  dob: undefined,
  gender: '',
  nationality: '',
  bvn: '',
  education: '',
  marital_status: '',
  number_of_children: '',
  current_address: '',
  email: '',
  phone_number: '',
  lga_of_origin: '',
  state_of_origin: '',
  city: '',
  state_of_residence: '',
  password: '',
  bvn_data: {
    bvn: '',
    first_name: '',
    last_name: '',
    middle_name: '',
    gender: '',
    date_of_birth: undefined,
    phone_number1: '',
    image: '',
    email: '',
    enrollment_bank: '',
    enrollment_branch: '',
    level_of_account: '',
    lga_of_origin: '',
    lga_of_residence: '',
    marital_status: '',
    name_on_card: '',
    nationality: '',
    nin: '',
    phone_number2: '',
    reference: '',
    registration_date: '',
    residential_address: '',
    state_of_origin: '',
    state_of_residence: '',
    title: '',
    watch_listed: '',
  },
};
